import { Poppins } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "./LayoutWrapper";

const _Poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["normal"],
  display: "swap",
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={_Poppins.variable}>
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
